Cherry pick of 3b418d7609a14c57a63fae18e92105a95ba03a5a failed
stdout:

stderr:
Performing inexact rename detection:  28% (924930/3241125)   Performing inexact rename detection:  29% (940410/3241125)   Performing inexact rename detection:  30% (973305/3241125)   Performing inexact rename detection:  31% (1006200/3241125)   Performing inexact rename detection:  32% (1037160/3241125)   Performing inexact rename detection:  33% (1070055/3241125)   Performing inexact rename detection:  34% (1102950/3241125)   Performing inexact rename detection:  35% (1135845/3241125)   Performing inexact rename detection:  36% (1166805/3241125)   Performing inexact rename detection:  37% (1199700/3241125)   Performing inexact rename detection:  38% (1232595/3241125)   Performing inexact rename detection:  39% (1265490/3241125)   Performing inexact rename detection:  40% (1296450/3241125)   Performing inexact rename detection:  41% (1329345/3241125)   Performing inexact rename detection:  42% (1362240/3241125)   Performing inexact rename detection:  43% (1395135/3241125)   Performing inexact rename detection:  44% (1426095/3241125)   Performing inexact rename detection:  45% (1458990/3241125)   Performing inexact rename detection:  46% (1491885/3241125)   Performing inexact rename detection:  47% (1524780/3241125)   Performing inexact rename detection:  48% (1555740/3241125)   Performing inexact rename detection:  49% (1588635/3241125)   Performing inexact rename detection:  50% (1621530/3241125)   Performing inexact rename detection:  51% (1654425/3241125)   Performing inexact rename detection:  52% (1685385/3241125)   Performing inexact rename detection:  53% (1718280/3241125)   Performing inexact rename detection:  54% (1751175/3241125)   Performing inexact rename detection:  55% (1784070/3241125)   Performing inexact rename detection:  56% (1815030/3241125)   Performing inexact rename detection:  57% (1847925/3241125)   Performing inexact rename detection:  58% (1880820/3241125)   Performing inexact rename detection:  59% (1913715/3241125)   Performing inexact rename detection:  60% (1944675/3241125)   Performing inexact rename detection:  61% (1977570/3241125)   Performing inexact rename detection:  62% (2010465/3241125)   Performing inexact rename detection:  63% (2043360/3241125)   Performing inexact rename detection:  64% (2074320/3241125)   Performing inexact rename detection:  65% (2107215/3241125)   Performing inexact rename detection:  66% (2140110/3241125)   Performing inexact rename detection:  67% (2173005/3241125)   Performing inexact rename detection:  68% (2203965/3241125)   Performing inexact rename detection:  69% (2236860/3241125)   Performing inexact rename detection:  70% (2269755/3241125)   Performing inexact rename detection:  71% (2302650/3241125)   Performing inexact rename detection:  72% (2333610/3241125)   Performing inexact rename detection:  73% (2366505/3241125)   Performing inexact rename detection:  74% (2399400/3241125)   Performing inexact rename detection:  75% (2432295/3241125)   Performing inexact rename detection:  76% (2463255/3241125)   Performing inexact rename detection:  77% (2496150/3241125)   Performing inexact rename detection:  78% (2529045/3241125)   Performing inexact rename detection:  79% (2561940/3241125)   Performing inexact rename detection:  80% (2592900/3241125)   Performing inexact rename detection:  81% (2625795/3241125)   Performing inexact rename detection:  81% (2633535/3241125)   Performing inexact rename detection:  82% (2658690/3241125)   Performing inexact rename detection:  83% (2691585/3241125)   Performing inexact rename detection:  84% (2722545/3241125)   Performing inexact rename detection:  85% (2755440/3241125)   Performing inexact rename detection:  86% (2788335/3241125)   Performing inexact rename detection:  87% (2821230/3241125)   Performing inexact rename detection:  88% (2852190/3241125)   Performing inexact rename detection:  89% (2885085/3241125)   Performing inexact rename detection:  90% (2917980/3241125)   Performing inexact rename detection:  91% (2950875/3241125)   Performing inexact rename detection:  92% (2981835/3241125)   Performing inexact rename detection:  93% (3014730/3241125)   Performing inexact rename detection:  94% (3047625/3241125)   Performing inexact rename detection:  95% (3080520/3241125)   Performing inexact rename detection:  96% (3111480/3241125)   Performing inexact rename detection:  97% (3144375/3241125)   Performing inexact rename detection:  98% (3177270/3241125)   Performing inexact rename detection:  99% (3210165/3241125)   Performing inexact rename detection: 100% (3241125/3241125)   Performing inexact rename detection: 100% (3241125/3241125), done.
error: could not apply 3b418d7609a... [FIX] l10n_fr: incorrect tax description
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/l10n_fr/data/account_tax_data.xml'