Cherry pick of af389f2b7cc7c58a4d3d98a7f5eab44edaf6f4ea failed
stdout:

stderr:
Performing inexact rename detection:   0% (140634/15192078)   Performing inexact rename detection:   1% (155058/15192078)   Performing inexact rename detection:   2% (306510/15192078)   Performing inexact rename detection:   3% (457962/15192078)   Performing inexact rename detection:   4% (609414/15192078)   Performing inexact rename detection:   5% (760866/15192078)   Performing inexact rename detection:   6% (912318/15192078)   Performing inexact rename detection:   7% (1063770/15192078)   Performing inexact rename detection:   8% (1218828/15192078)   Performing inexact rename detection:   9% (1370280/15192078)   Performing inexact rename detection:  10% (1521732/15192078)   Performing inexact rename detection:  11% (1673184/15192078)   Performing inexact rename detection:  12% (1824636/15192078)   Performing inexact rename detection:  13% (1976088/15192078)   Performing inexact rename detection:  13% (2012148/15192078)   Performing inexact rename detection:  14% (2127540/15192078)   Performing inexact rename detection:  15% (2278992/15192078)   Performing inexact rename detection:  16% (2434050/15192078)   Performing inexact rename detection:  17% (2585502/15192078)   Performing inexact rename detection:  18% (2736954/15192078)   Performing inexact rename detection:  19% (2888406/15192078)   Performing inexact rename detection:  20% (3039858/15192078)   Performing inexact rename detection:  21% (3191310/15192078)   Performing inexact rename detection:  22% (3342762/15192078)   Performing inexact rename detection:  23% (3494214/15192078)   Performing inexact rename detection:  24% (3649272/15192078)   Performing inexact rename detection:  25% (3800724/15192078)   Performing inexact rename detection:  26% (3952176/15192078)   Performing inexact rename detection:  27% (4103628/15192078)   Performing inexact rename detection:  28% (4255080/15192078)   Performing inexact rename detection:  29% (4406532/15192078)   Performing inexact rename detection:  29% (4417350/15192078)   Performing inexact rename detection:  30% (4557984/15192078)   Performing inexact rename detection:  31% (4713042/15192078)   Performing inexact rename detection:  32% (4864494/15192078)   Performing inexact rename detection:  33% (5015946/15192078)   Performing inexact rename detection:  34% (5167398/15192078)   Performing inexact rename detection:  35% (5318850/15192078)   Performing inexact rename detection:  36% (5470302/15192078)   Performing inexact rename detection:  37% (5621754/15192078)   Performing inexact rename detection:  38% (5773206/15192078)   Performing inexact rename detection:  39% (5928264/15192078)   Performing inexact rename detection:  40% (6079716/15192078)   Performing inexact rename detection:  41% (6231168/15192078)   Performing inexact rename detection:  42% (6382620/15192078)   Performing inexact rename detection:  43% (6534072/15192078)   Performing inexact rename detection:  44% (6685524/15192078)   Performing inexact rename detection:  45% (6836976/15192078)   Performing inexact rename detection:  46% (6988428/15192078)   Performing inexact rename detection:  46% (7071366/15192078)   Performing inexact rename detection:  47% (7143486/15192078)   Performing inexact rename detection:  48% (7302150/15192078)   Performing inexact rename detection:  49% (7446390/15192078)   Performing inexact rename detection:  50% (7597842/15192078)   Performing inexact rename detection:  51% (7749294/15192078)   Performing inexact rename detection:  52% (7900746/15192078)   Performing inexact rename detection:  53% (8052198/15192078)   Performing inexact rename detection:  54% (8207256/15192078)   Performing inexact rename detection:  55% (8358708/15192078)   Performing inexact rename detection:  56% (8510160/15192078)   Performing inexact rename detection:  57% (8661612/15192078)   Performing inexact rename detection:  58% (8813064/15192078)   Performing inexact rename detection:  59% (8964516/15192078)   Performing inexact rename detection:  60% (9115968/15192078)   Performing inexact rename detection:  61% (9267420/15192078)   Performing inexact rename detection:  61% (9343146/15192078)   Performing inexact rename detection:  62% (9422478/15192078)   Performing inexact rename detection:  63% (9573930/15192078)   Performing inexact rename detection:  64% (9725382/15192078)   Performing inexact rename detection:  65% (9876834/15192078)   Performing inexact rename detection:  66% (10028286/15192078)   Performing inexact rename detection:  67% (10179738/15192078)   Performing inexact rename detection:  68% (10331190/15192078)   Performing inexact rename detection:  69% (10482642/15192078)   Performing inexact rename detection:  70% (10637700/15192078)   Performing inexact rename detection:  71% (10789152/15192078)   Performing inexact rename detection:  72% (10940604/15192078)   Performing inexact rename detection:  73% (11092056/15192078)   Performing inexact rename detection:  74% (11243508/15192078)   Performing inexact rename detection:  75% (11394960/15192078)   Performing inexact rename detection:  76% (11560836/15192078)   Performing inexact rename detection:  77% (11701470/15192078)   Performing inexact rename detection:  78% (11852922/15192078)   Performing inexact rename detection:  79% (12004374/15192078)   Performing inexact rename detection:  80% (12155826/15192078)   Performing inexact rename detection:  81% (12307278/15192078)   Performing inexact rename detection:  81% (12379398/15192078)   Performing inexact rename detection:  82% (12458730/15192078)   Performing inexact rename detection:  83% (12610182/15192078)   Performing inexact rename detection:  84% (12761634/15192078)   Performing inexact rename detection:  85% (12916692/15192078)   Performing inexact rename detection:  86% (13068144/15192078)   Performing inexact rename detection:  87% (13219596/15192078)   Performing inexact rename detection:  88% (13371048/15192078)   Performing inexact rename detection:  89% (13522500/15192078)   Performing inexact rename detection:  90% (13673952/15192078)   Performing inexact rename detection:  91% (13825404/15192078)   Performing inexact rename detection:  92% (13976856/15192078)   Performing inexact rename detection:  93% (14131914/15192078)   Performing inexact rename detection:  94% (14283366/15192078)   Performing inexact rename detection:  95% (14434818/15192078)   Performing inexact rename detection:  96% (14586270/15192078)   Performing inexact rename detection:  97% (14737722/15192078)   Performing inexact rename detection:  98% (14889174/15192078)   Performing inexact rename detection:  99% (15040626/15192078)   Performing inexact rename detection: 100% (15192078/15192078)   Performing inexact rename detection: 100% (15192078/15192078), done.
error: could not apply af389f2b7cc... [FIX] account: payment keep move names on cancel
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/account/models/account_payment.py'
Recorded preimage for 'addons/account/tests/test_payment.py'